### ISSUE TITLE
Metamod 2.0 build 1284 with this addon crashes the server

### ISSUE THREAD

**Issue by BoTo-sg** [Source2ZE/MultiAddonManager#1]
Metamod 2.0 build 1284 with this addon crashes the server, disabling MultiAddonManager fixes the server crashes.

**Comment by xen-000** [comment]
This is because there was a breaking hl2sdk change, I'll fix it soon.

**Comment by BoTo-sg** [comment]
Updated to MultiAddonManager 1.2 and server crashes are fixed.
