### ISSUE TITLE
Console outputs double things since MultiAddonsManager

### ISSUE THREAD

**Issue by freakexeuLow** [Source2ZE/MultiAddonManager#10]
Hey, since i installed the metamod plugin, i get double output. if i deactivate it, everything is normal again

**Example**

```
sv_pure value unchanged (current value is 0).
--------------------------------------------------------
--------------------------------------------------------
sv_pure value unchanged (current value is 0).
execing cs2-retakes/retakes.cfg
execing cs2-retakes/retakes.cfg
Unknown command '�'!
[Retakes] Config loaded!
Unknown command '�'!
[Retakes] Config loaded!
17:32:55 [INFO] (cssharp:AdminManager) Loaded admin data with 3 admins.
17:32:55 [INFO] (cssharp:AdminManager) Loaded admin data with 3 admins.
Loaded 4 admin groups.
Loaded 4 admin groups.
```

**Comment by Vauff** [comment]
First map is reloaded at server startup to ensure the addon is properly mounted, this other plugin output could simply be coming from some OnMapStart hook.

**Comment by freakexeuLow** [comment]
> First map is reloaded at server startup to ensure the addon is properly mounted, this other plugin output could simply be coming from some OnMapStart hook.

ahh so it's normal, I just noticed it because I've only had the “problem” since the MultiModManager, thanks for the answer anyway  and thanks for the answer @Vauff 👍🏼
