### ISSUE TITLE
Unable to download and mount plugin

### ISSUE THREAD

**Issue by gjonezin** [Source2ZE/MultiAddonManager#13]
Hi. Thank you for the work you've done on this plugin. However, I'm struggling to figure out where I am to include the public header, as well as how to query the interface in 'AllPluginsLoaded' as you've indicated in your instructions. I apologize in advance, as I am new to all this. Also, I'm assuming that is the next step in order to get this to work. Please, see below.

To provide some context; I've recently set up a CS2 server on a dedicated PC running windows 10 home build 19045. I've added Metamod, Counterstriksharp (with no block), and CS2 fixes to enable the zombie reborn mod. The zombie mod is currently working. But, I'm trying to add in some actual zombie skins. I'm trying to add workshop item 3170427476. I continue to get "Addon 789 failed to download with status 9" and the zombies are still in default skins (completely red humans t/cts).

Any help would be greatly appreciated. Thanks again.

<img width="1876" alt="CS2 server unable to download plugin" src="https://github.com/user-attachments/assets/47d7a3e8-96b1-42dd-928f-f6e2d899f4ea">

**Comment by Poggicek** [comment]
The metamod interface is exposed for developers that might want to interact with the plugin, end users only have to use the config nad not touch that interface at all

**Comment by gjonezin** [comment]
> The metamod interface is exposed for developers that might want to interact with the plugin, end users only have to use the config and not touch that interface at all

The config did not allow for downloading and mounting the workshop models. In the Cs2 fixes config, instructions for end users indicated needing this plugin to precache, as mentioned. This plugin is not downloading and mounting the workshop item with the config.

After reading here, it looks like it's due to having other plugins. I've come this far. I just need to know where I need to enter the public header and query the interface. Otherwise, is there something I am missing for this to work in conjunction with the Cs2 fixes zombie mod?

**Comment by xen-000** [comment]
First of all as poggu said, you don't need the header as you're not developing a metamod plugin. Secondly, did you try to do `mm_extra_addons` in the console to check its current value, there might be an issue with your config or where you placed it.

**Comment by gjonezin** [comment]
My apologies then. I didn't mean to waste your time. I have, and it just returns the same prompt.

**Comment by gjonezin** [comment]
SOLVED - I just downloaded it manually using SteamCMD, force_install_dir {Path} of course, and then workshop_download_item {AppID} {WorkshopID}; e.g. workshop_download_item 730 3070595459 in my case. I then downloaded Source2viewer to open the vpk file model names. Then, I inserted it in the "modelname" above--Restart server--Just in case anyone else finds themself here.
