### ISSUE TITLE
Players are not disconnected if map update should be loaded

### ISSUE THREAD

**Issue by ssypchenko** [Source2ZE/MultiAddonManager#14]
Players will not be disconnected from the server during map changes and will need to manually disconnect and reconnect if a map needs to be downloaded or reloaded from the workshop.  If the map is updated on both the server and the client, the player will normally be disconnected at the map change and reconnected to load the new map.

**Comment by xen-000** [comment]
Yes I'm aware of this bug, it mostly happens when you're running 2 or more extra addons, but also *sometimes* even running 1 addon. The last game update caused this and so far I can't think of a clean solution to it.

**Comment by xen-000** [comment]
I've pushed a new [release](https://github.com/Source2ZE/MultiAddonManager/releases/tag/v1.2.10) with a fix, let me know if it all works now.

**Comment by ssypchenko** [comment]
I think it works now. We will do more tests, but at first glance, it seems to work. Thank you very much!
