### ISSUE TITLE
Doesn't log into the server after adding a collection to the config

### ISSUE THREAD

**Issue by AWDScroll** [Source2ZE/MultiAddonManager#18]
I encountered a problem that after yesterday's update I can't log into the server if the collection is written in the config, every time either "You have been disconnected" or I just re-log into the server 10 times, after deleting the collection from the config everything works fine

**Comment by fpaezf** [comment]
same

**Comment by xen-000** [comment]
You're not supposed to put a collection in the config, only individual workshop submissions will work.
