### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by xLeviNx** [Source2ZE/MultiAddonManager#2]
![image](https://github.com/Source2ZE/MultiAddonManager/assets/48465241/fd473fff-23eb-4931-817b-b58a80b6cf6c)

There seems to be console spam with the latest release.

This is in combination of the latest CS2Fixes release (1.6) and CS# although I doubt they're related to this

**Comment by xen-000** [comment]
The console message is printed whenever an addon is downloaded. As this is a standard steam API callback, it will be called even when the server downloads/updates a map, not sure what makes the server initiate so many downloads though.

**Comment by Vauff** [comment]
That addon was stuck in Steam approval hell at the time of this report, which likely prevented the download from correctly finishing here.

**Comment by xLeviNx** [comment]
Closing this since that could be the reason
