### ISSUE TITLE
Music from Workshop Maps Not Playing with MultiAddonManager

### ISSUE THREAD

**Issue by wjdrkfka3** [Source2ZE/MultiAddonManager#22]
When using MultiAddonManager, the music from Workshop maps does not play as expected. 
Disabling MultiAddonManager resolves the issue. 
Please investigate and provide a fix or workaround.

**Comment by STONE-GPY** [comment]
If your addon has soundevents_addon.vsndevts file in sounds.
It will override soundevents_addon.vsndevts in workshop map and sound will not played.
Check your addon has soundevents_addon.vsndevts

**Comment by Vauff** [comment]
This is an issue with your server addon as STONE explained.
