### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by menesakdeniz** [Source2ZE/MultiAddonManager#3]
Hi,

This extension crashes the server if you start the server with "+host_workshop_collection id" parameter.

**Comment by xLeviNx** [comment]
It does not. I am currently running it with that parameter.

**Comment by menesakdeniz** [comment]
Command line arguments;
- -ip localip -maxplayers 40 -dedicated -port 27015 -game csgo -console +game_type 0 +game_mode 0 +map de_dust2 +exec server.cfg +net_public_adr ip +sv_setsteamaccount xxx -nobots +host_workshop_collection 3070739825
Result;
<img width="654" alt="crashed" src="https://github.com/Source2ZE/MultiAddonManager/assets/24219979/379b1579-04ce-4512-aab7-8ac4ee742d44">

Command line arguments;
- -ip localip -maxplayers 40 -dedicated -port 27015 -game csgo -console +game_type 0 +game_mode 0 +map de_dust2 +exec server.cfg +net_public_adr ip +sv_setsteamaccount xxx -nobots
Result;
No crash
<img width="1047" alt="2" src="https://github.com/Source2ZE/MultiAddonManager/assets/24219979/ab8efe0d-932f-49a4-807a-ae3ce1d45a59">

**Comment by xLeviNx** [comment]
./game/cs2.sh -dedicated +ip 64.74.163.82 -port 27015 +map de_dust2 -maxplayers 64 +sv_setsteamaccount xx -authkey xx +host_workshop_collection "3155358384" +game_mode 0 +game_type 0

This is my start up. 

```
  [01] AcceleratorCS2 (1.0.0) by Poggu, Phoenix (˙·٠●Феникс●٠·˙), Asher Baker (asherkin)
  [02] ServerListPlayersFix (1.0.0.0) by Poggu
  [03] CounterStrikeSharp (0.1.0) by Roflmuffin
  [04] CS2Fixes (1.6) by xen, Poggu, and the Source2ZE community
  [05] MultiAddonManager (1.2) by xen
  [06] CleanerCS2 (1.0.2) by Poggu
```

Is your server on windows?

**Comment by brkvlr** [comment]
No, linux.

**Comment by menesakdeniz** [comment]
Do you have any idea how find what is causing this error?
We don't have any -authkey parameters, Could it be because of this?

**Comment by xLeviNx** [comment]
Not sure. Test the latest and see if anything happens

**Comment by menesakdeniz** [comment]
It's still crashing even with latest version.

**Comment by xLeviNx** [comment]
Still not able to replicate this issue. Maybe add the auth key and see? Required for workshop afaik

**Comment by Vauff** [comment]
> Still not able to replicate this issue. Maybe add the auth key and see? Required for workshop afaik

Only was needed for CS:GO's old roundabout workshop implementation.

**Comment by menesakdeniz** [comment]
Result is same with authkey.
Is there any debug mode that I can activate to provide better logs?

**Comment by Vauff** [comment]
> Result is same with authkey. Is there any debug mode that I can activate to provide better logs?

[AcceleratorCS2](https://github.com/Source2ZE/AcceleratorCS2)

**Comment by menesakdeniz** [comment]
Seems like it's fixed in the latest releases.
